"""
deploy.py — ABC Lubrication Data Pipeline 部署腳本

執行方式：
  python scripts/deploy.py

功能：
  1. 確認三個 master Excel 均存在
  2. git add output/ registry/ logs/ scripts/ lube_query_app.html .gitignore CLAUDE.md
  3. git commit -m "data: update [YYYY-MM-DD HH:MM]"
  4. git push origin main
  5. 寫入 logs/update_log.txt

前置條件：
  - 已執行 git init 並設定 remote origin
  - 已設定 git user.name / user.email
  - GitHub 認證（PAT 或 SSH key）
"""

import subprocess
import sys
import os
import json
from datetime import datetime
from pathlib import Path

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _config import (
    PROJECT, OUT_DIR, LOG_FILE as LOG_FILE_STR,
    LC_MASTER, NB_MASTER, OEM_MASTER,
    APP_HTML as APP_HTML_STR, APP_DATA_JS as APP_DATA_JS_STR,
    DISPLAY_COLS, SRC_ORDER,
)

# ── 路徑（轉為 Path 物件以維持 deploy.py 既有 API） ─────────────
BASE_DIR    = Path(PROJECT)
OUTPUT_DIR  = Path(OUT_DIR)
LOG_FILE    = Path(LOG_FILE_STR)
APP_HTML    = Path(APP_HTML_STR)
APP_DATA_JS = Path(APP_DATA_JS_STR)

REQUIRED_FILES = [Path(LC_MASTER), Path(NB_MASTER), Path(OEM_MASTER)]

# 要加入 git 的路徑
GIT_ADD_TARGETS = [
    "output/lube_chart_master.xlsx",
    "output/nb_master.xlsx",
    "output/oem_master.xlsx",
    "output/app_data.js",
    "registry/",
    "logs/",
    "scripts/",
    "lube_query_app.html",
    ".gitignore",
    "CLAUDE.md",
]

# ── App 資料重建（寫入 output/app_data.js，HTML 不動）─────────
def rebuild_app_data() -> bool:
    """
    讀取三個 master Excel，合併為 DATA（不含 source_file/source_sheet），
    依 OEM > NB > LUBE CHART 排序後寫入 output/app_data.js。
    MAKERS 由 DATA 的 Maker 欄去重排序自動產生。
    """
    frames = []

    lube_master = OUTPUT_DIR / "lube_chart_master.xlsx"
    nb_master   = OUTPUT_DIR / "nb_master.xlsx"
    oem_master  = OUTPUT_DIR / "oem_master.xlsx"

    if lube_master.exists():
        try:
            df = pd.read_excel(lube_master, sheet_name='lube_chart')
            for col in DISPLAY_COLS:
                if col not in df.columns:
                    df[col] = 1 if col == 'Count' else ''
            frames.append(df[DISPLAY_COLS].copy())
        except Exception as e:
            print(f"  ⚠ 讀取 lube_chart_master.xlsx 失敗：{e}")

    if nb_master.exists():
        try:
            df = pd.read_excel(nb_master, sheet_name='nb_master')
            for col in DISPLAY_COLS:
                if col not in df.columns:
                    df[col] = 1 if col == 'Count' else ''
            frames.append(df[DISPLAY_COLS].copy())
        except Exception as e:
            print(f"  ⚠ 讀取 nb_master.xlsx 失敗：{e}")

    if oem_master.exists():
        try:
            df_oem = pd.read_excel(oem_master, sheet_name='manual_data')
        except Exception as e:
            print(f"  ⚠ 讀取 oem_master.xlsx (manual_data) 失敗：{e}")
            df_oem = pd.DataFrame()
        for col in DISPLAY_COLS:
            if col not in df_oem.columns:
                df_oem[col] = 1 if col == 'Count' else ''
        # OEM 導入 app 前：所有文字欄位全大寫 + 去除前後空白
        df_oem = df_oem[DISPLAY_COLS].copy()
        for col in DISPLAY_COLS:
            if col == 'Count':
                continue
            df_oem.loc[:, col] = df_oem[col].fillna('').astype(str).str.strip().str.upper()
        frames.append(df_oem)

    if not frames:
        print("  ⚠ 無資料可寫入 app_data.js，跳過")
        return False

    df_all = pd.concat(frames, ignore_index=True).copy()
    for col in DISPLAY_COLS:
        if col == 'Count':
            df_all.loc[:, col] = pd.to_numeric(df_all[col], errors='coerce').fillna(1).astype(int)
        else:
            df_all.loc[:, col] = df_all[col].fillna('').astype(str).str.strip()

    df_all.loc[:, '_order'] = df_all['Source'].map(SRC_ORDER).fillna(3).astype(int)
    df_all = df_all.sort_values(['_order', 'Maker', 'Model / Type'])
    # 跨來源去重：以 Maker + Model/Type + Part + Lubricant 為鍵，重複時保留 OEM（_order 最小者）
    dedup_keys = ['Maker', 'Model / Type', 'Part to be lubricated', 'Lubricant']
    before = len(df_all)
    df_all = df_all.drop_duplicates(subset=dedup_keys, keep='first')
    removed = before - len(df_all)
    if removed:
        print(f"  ✓ 跨來源去重：移除 {removed:,} 筆重複（保留 OEM 優先）")
    df_all = df_all.drop(columns=['_order']).reset_index(drop=True)

    records   = df_all.to_dict(orient='records')
    data_json = json.dumps(records, ensure_ascii=False, separators=(',', ':'))

    makers = sorted({m for m in df_all['Maker'].tolist() if m})
    makers_json = json.dumps(makers, ensure_ascii=False, separators=(',', ':'))

    APP_DATA_JS.parent.mkdir(parents=True, exist_ok=True)
    APP_DATA_JS.write_text(
        '// Auto-generated by scripts/deploy.py — do not edit by hand.\n'
        f'const DATA = {data_json};\n'
        f'const MAKERS = {makers_json};\n',
        encoding='utf-8'
    )
    size_mb = APP_DATA_JS.stat().st_size / 1024 / 1024
    print(f"  ✓ output/app_data.js 重建完成（DATA {len(records):,} 筆 / MAKERS {len(makers):,} 筆，{size_mb:.2f} MB）")
    return True


# ── Helper ────────────────────────────────────────────────────
def run(cmd: list[str], cwd=None) -> tuple[int, str, str]:
    """執行 shell 指令，回傳 (returncode, stdout, stderr)"""
    result = subprocess.run(
        cmd,
        cwd=cwd or BASE_DIR,
        capture_output=True,
        text=True
    )
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def log(message: str):
    """印出並附加至 log 檔"""
    print(message)
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(message + "\n")


def append_deploy_log(commit_hash: str, success: bool, error_msg: str = ""):
    """在 update_log.txt 末端附加部署記錄"""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    separator = "=" * 40
    lines = [
        separator,
        f"時間：{now}",
        "動作：部署（GitHub + Vercel）",
        "-" * 40,
    ]
    if success:
        lines.append(f"Git commit：{commit_hash}")
        lines.append("推送至 GitHub：✓")
        lines.append("Vercel 部署：已透過 webhook 自動觸發")
    else:
        lines.append(f"❌ 部署失敗：{error_msg}")
    lines.append(separator)

    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


# ── 主流程 ────────────────────────────────────────────────────
def main():
    print("=" * 50)
    print("🚀 ABC Lubrication — 部署流程開始")
    print("=" * 50)

    # 1. 確認 master Excel 均存在
    print("\n[1/5] 確認 master Excel 檔案...")
    missing = [f for f in REQUIRED_FILES if not f.exists()]
    if missing:
        for m in missing:
            print(f"  ❌ 缺少：{m.name}")
        print("\n請先執行 process 腳本產生 master Excel 後再部署。")
        sys.exit(1)
    for f in REQUIRED_FILES:
        print(f"  ✓ {f.name}")

    # 2. 重建 App 資料（output/app_data.js，HTML 為靜態樣板不動）
    print("\n[2/5] 重建 output/app_data.js（DATA + MAKERS）...")
    rebuild_app_data()

    # 3. Git add
    print("\n[3/5] 加入 git staging area...")
    for target in GIT_ADD_TARGETS:
        full_path = BASE_DIR / target
        if Path(str(full_path)).exists() or target.endswith("/"):
            code, out, err = run(["git", "add", target])
            if code != 0:
                print(f"  ⚠ git add {target} 警告：{err}")
            else:
                print(f"  ✓ git add {target}")
        else:
            print(f"  ⚠ 略過（不存在）：{target}")

    # 確認是否有任何改動
    code, out, err = run(["git", "status", "--porcelain"])
    if not out.strip():
        print("\n📋 沒有需要 commit 的改動，部署流程結束。")
        return

    # 4. Git commit
    print("\n[4/5] 建立 commit...")
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    commit_msg = f"data: update {now_str}"
    code, out, err = run(["git", "commit", "-m", commit_msg])
    if code != 0:
        print(f"  ❌ commit 失敗：{err}")
        append_deploy_log("", False, err)
        sys.exit(1)

    # 取得 commit hash
    code2, commit_hash, _ = run(["git", "rev-parse", "--short", "HEAD"])
    print(f"  ✓ commit：{commit_hash}  \"{commit_msg}\"")

    # 5. Git push
    print("\n[5/5] 推送至 GitHub...")
    code, out, err = run(["git", "push", "origin", "main"])
    if code != 0:
        # 嘗試設定 upstream 再推送
        code, out, err = run(["git", "push", "--set-upstream", "origin", "main"])
    if code != 0:
        print(f"  ❌ push 失敗：{err}")
        print("\n提示：如果是認證問題，請確認已設定 GitHub PAT 或 SSH key。")
        append_deploy_log(commit_hash, False, err)
        sys.exit(1)

    print("  ✓ 推送成功！")
    print("\n✅ Vercel 將透過 webhook 自動觸發部署，請至 Vercel Dashboard 確認狀態。")

    append_deploy_log(commit_hash, True)

    print("\n" + "=" * 50)
    print("🎉 部署完成！")
    print("=" * 50)


if __name__ == "__main__":
    main()
